services:
  youtube-dl:
    build: .
    container_name: youtube-dl-server
    ports:
      - "8082:80"
    volumes:
      - "/media/blake/Seagate Portable Drive/data/yt:/downloads"
    restart: unless-stopped
